
# 开发环境配置
server:
      servlet:
            # 应用的访问路径
            context-path: /
      tomcat:
            # tomcat的URI编码
            uri-encoding: UTF-8
            # 连接数满后的排队数，默认为100
            accept-count: 1000
            threads:
                  # tomcat最大线程数，默认为200
                  max: 800
                  # Tomcat启动初始化的线程数，默认值10
                  min-spare: 100

logging:
      config: classpath:logback-boot.xml
      #level:
            #包下的所有 mapper 日志输出级别为 trace，会将操作数据库的 sql 打印出来，开发时设置成 trace 方便定位问题
            #com.itcodai.course03.dao: trace

spring:
      devtools:
            restart:
                  enabled: true # 热部署开关，重新build可更新

productorder:
      test: 999
      userinfo:
            name: productorder-userinfo
      orderinfo:
            name: productorder-orderinfo
      product:
            name: productorder-product
      productline:
            name: productorder-productline
      warehouse:
            name: productorder-warehouse

