

spring.datasource.dynamic:
      datasource:
        # 设置 账号数据源配置
        test1-ds:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/test1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&allowMultiQueries=true
          username: root
          password: 123456
          # 设置 订单数据源配置
        test2-ds:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/test2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&allowMultiQueries=true
          username: root
          password: 123456
          # 设置商品 数据源配置
        test3-ds:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/test3?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false&allowMultiQueries=true
          username: root
          password: 123456
      # 设置默认数据源或者数据源组 默认值即为master
      primary: test1-ds # 默认指定一个数据源
      # 开启对 seata的支持
      seata: true






