
# Redis
spring.redis:
  host: ${REDIS_HOST:127.0.0.1}
  port: ${REDIS_PORT:6379}
  #database: 0
  #password: ${REDIS_PASSWORD:123456}
  pool:
    maxTotal: 600 #最大连接数(默认:8)
    maxIdle: 300 #最大空闲数(默认:8)
    maxWaitMillis: 1000 #当连接池资源耗尽时,调用者最大阻塞时间,超时将抛出异常.单位:毫秒,默认:-1,表示永不超时.
    testOnBorrow: true #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个 (默认:false)








